<?php
/**
 * EcomitizeFaq related module
 *
 * @category    YanMalinovsky
 * @package     YanMalinovsky_EcomitizeFaq
 * @copyright   Copyright (c) 2016 Yan Malinovsky
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $faq = $this->getActiveFaq()->getData() ?>

<?php if ($faq): ?>
    <?php $faq = $faq[array_rand($faq)] ?>
    <hr />
    <ul>
        <li><?php echo "{$this->__('Question: ')} {$faq['question']}" ?></li>
        <li><?php echo "{$this->__('Answer: ')} {$faq['answer']}" ?></li>
    </ul>
    <hr />
<?php endif; ?>
